name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Blog_Projeto/Blog_Projeto.sln              # Caminho correto para o arquivo de solução
      Test_Project_Path: Blog_Projeto/Blog_Projeto.Tests/Blog_Projeto.Tests.csproj  # Caminho do projeto de testes (caso exista)
      Wap_Project_Directory: Blog_Projeto/Blog_Projeto.Package   # Substitua com o diretório do projeto WAP (Windows Application Packaging)
      Wap_Project_Path: Blog_Projeto/Blog_Projeto.Package/Blog_Projeto.Package.wapproj  # Caminho para o arquivo .wapproj do seu projeto WAP

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Instalar o .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Configurar MSBuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Executar os testes unitários
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name  # Usando o caminho correto para a solução

    # Restaurar a aplicação
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Decodificar o arquivo pfx e salvar o certificado
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Criar o pacote da aplicação
    - name: Create the app package
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Remover o arquivo pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Fazer o upload dos artefatos (pacote MSIX)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
